# Generated by Django 6.1.1 on 2026-10-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0009_remove_topic_created_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expense',
            table='pool2_ausgabe',
        ),
    ]
